-- Inizializzazione di appdb: account di servizio, schemi, tabelle e dati di seed.
-- Eseguito una sola volta da docker-entrypoint-initdb.d al primo avvio
-- (o dopo "just down -v" che cancella il named volume pgdata).

-- ── Account di servizio ──────────────────────────────────────────────────────
CREATE USER user_svc    WITH PASSWORD 'user_svc';
CREATE USER product_svc WITH PASSWORD 'product_svc';

CREATE SCHEMA user_svc    AUTHORIZATION user_svc;
CREATE SCHEMA product_svc AUTHORIZATION product_svc;

GRANT CONNECT ON DATABASE appdb TO user_svc, product_svc;

-- ── Schema user_svc ──────────────────────────────────────────────────────────
CREATE TABLE user_svc.users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA user_svc TO user_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA user_svc TO user_svc;

-- Seed: 100 utenti con id espliciti 1-100
INSERT INTO user_svc.users (id, name, email, created_at)
SELECT
    gs,
    'User '  || gs,
    'user'   || gs || '@example.com',
    NOW()
FROM generate_series(1, 100) AS gs;

-- Avanza la sequence oltre gli id seedati
ALTER TABLE user_svc.users ALTER COLUMN id RESTART WITH 101;

-- ── Schema product_svc ───────────────────────────────────────────────────────
CREATE TABLE product_svc.products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    sku         VARCHAR(255) NOT NULL,
    price_cents INT          NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA product_svc TO product_svc;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA product_svc TO product_svc;

-- Seed: 100 prodotti con id espliciti 1-100
INSERT INTO product_svc.products (id, name, sku, price_cents, created_at)
SELECT
    gs,
    'Product ' || gs,
    'SKU-'     || LPAD(gs::text, 3, '0'),
    100 + gs * 10,
    NOW()
FROM generate_series(1, 100) AS gs;

ALTER TABLE product_svc.products ALTER COLUMN id RESTART WITH 101;
